name: backfill-pipeline
services:
  trades-producer-historical:
    build: 
      context: ../services/trade_producer
      dockerfile: Dockerfile
    container_name: trades-producer-historical
    restart: on-failure
    tty: true
    volumes:
      - "../services/trade_producer/app:/code/app"
    networks:
      - redpanda_network
    env_file:
      - ../services/trade_producer/.env.historical.prod
    environment:
      - BACKFILL_JOB_ID=${BACKFILL_JOB_ID}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: ["python","-m", "app.main"]


  trades-to-ohlcv-historical:
    build: 
      context: ../services/trade_to_ohlcv
      dockerfile: Dockerfile
    container_name: trades-to-ohlcv-historical
    restart: on-failure
    tty: true
    volumes:
      - "../services/trade_to_ohlcv/app:/code/app"
    networks:
      - redpanda_network
    env_file:
      - ../services/trade_to_ohlcv/.env.historical.prod
    environment:
      - BACKFILL_JOB_ID=${BACKFILL_JOB_ID}
    depends_on:
      - trades-producer-historical
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: ["python","-m", "app.main"]

  topic-to-feature-store-historical:
    build: 
      context: ../services/topic_to_feature_store
      dockerfile: Dockerfile
    container_name: topic-to-feature-store-historical
    restart: on-failure
    tty: true
    volumes:
      - "../services/topic_to_feature_store/app:/code/app"
    networks:
      - redpanda_network
    env_file:
      - ../services/topic_to_feature_store/.env.historical.prod
    environment:
      - BACKFILL_JOB_ID=${BACKFILL_JOB_ID}
    depends_on:
      - trades-to-ohlcv-historical
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: ["python","-m", "app.main"]


networks:
    redpanda_network:
      external: true
      name: redpanda_network