services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    networks:
      - redpanda_network
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native interface
      - "9009:9009"   # Inter-server communication port
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=clickhouse_password
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 30s
      timeout: 5s
      retries: 3

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    networks:
      - redpanda_network
    ports:
      - "8978:8978"
    volumes:
      - dbeaver_workspace:/opt/cloudbeaver/workspace
    depends_on:
      - clickhouse
    environment:
      - CBV_ADMIN_NAME=admin
      - CBV_ADMIN_PASSWORD=dbeaver_password

volumes:
  clickhouse_data:
  clickhouse_logs:
  dbeaver_workspace:


networks:
    redpanda_network:
      external: true
      name: redpanda_network