name: feature-pipeline
services:
  trades-producer:
    build: 
      context: ../services/trade_producer
      dockerfile: Dockerfile
    container_name: trades-producer
    restart: unless-stopped
    tty: true
    volumes:
      - "../services/trade_producer/app:/code/app"
    networks:
      - redpanda_network
    env_file:
      - ../services/trade_producer/.env.live.prod
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: ["python","-m", "app.main"]

  trades-to-ohlcv:
    build: 
      context: ../services/trade_to_ohlcv
      dockerfile: Dockerfile
    container_name: trades-to-ohlcv
    restart: unless-stopped
    tty: true
    volumes:
      - "../services/trade_to_ohlcv/app:/code/app"
    networks:
      - redpanda_network
    env_file:
      - ../services/trade_to_ohlcv/.env.live.prod
    depends_on:
      - trades-producer
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: ["python","-m", "app.main"]

  topic-to-feature-store:
    build: 
      context: ../services/topic_to_feature_store
      dockerfile: Dockerfile
    container_name: topic-to-feature-store
    restart: unless-stopped
    tty: true
    volumes:
      - "../services/topic_to_feature_store/app:/code/app"
    networks:
      - redpanda_network
    env_file:
      - ../services/topic_to_feature_store/.env.live.prod
    depends_on:
      - trades-to-ohlcv
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: ["python","-m", "app.main"]

networks:
    redpanda_network:
      external: true
      name: redpanda_network