start-redpanda:
	docker compose -f redpanda.yml up -d

stop-redpanda:
	docker compose -f redpanda.yml down

start-feature-live-pipeline:
	docker compose -f feature_live_pipeline.yml up -d

stop-feature-live-pipeline:
	docker compose -f feature_live_pipeline.yml down